#
# AWS IoT Greengrass component recipe reference
# https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html
#
RecipeFormatVersion: 2020-01-25
ComponentName: dev.hisa.Ninja-prod
ComponentVersion: '1.0.31'
ComponentDescription: Ninja qPCR Greengrass component
ComponentPublisher: Toriningen Inc.
ComponentConfiguration:
  DefaultConfiguration:
    NINJAQPCR_SRC: /usr/local/ninjaqpcr
    NINJAQPCR_DATA: /var/lib/ninjaqpcr/data
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: s3://gg-ninja-qpcr/artifacts/dev.hisa.Ninja/1.0.31/src-prod.zip
        Unarchive: ZIP
    Lifecycle:
      Bootstrap:
        RequiresPrivilege: true
        Script: |
          VERSION=`sh {artifacts:decompressedPath}/src-prod/src/greengrass/version.sh {artifacts:decompressedPath}/src-prod/src/greengrass/recipe/prod.yaml`
          echo "[NinjaPCR] Bootstrap ver$VERSION"
          echo "configuration:/NINJAQPCR_SRC={configuration:/NINJAQPCR_SRC}"
          ln -f -s {artifacts:decompressedPath}/src-prod/src {configuration:/NINJAQPCR_SRC}
          cd {configuration:/NINJAQPCR_SRC}/qpcr
          echo y | npm update
          cd {configuration:/NINJAQPCR_SRC}/console/server
          echo y | npm update
          if [ `grep NINJAQPCR_VERSION /etc/profile | wc -l` -eq 0 ]; then
            echo "export NINJAQPCR_VERSION=$VERSION" | tee -a /etc/profile
          else
            sed -i "s/export NINJAQPCR_VERSION=.*/export NINJAQPCR_VERSION=$VERSION/" /etc/profile
          fi
          exit 0
      Install:
        Script: |
          VERSION=`sh {artifacts:decompressedPath}/src-prod/src/greengrass/version.sh {artifacts:decompressedPath}/src-prod/src/greengrass/recipe/prod.yaml`
          echo "[NinjaPCR] Install ver$VERSION"
      Run:
        Script: |
          #python3 {configuration:/NINJAQPCR_SRC}/greengrass/recipe/hello_world2.py
          VERSION=`sh {artifacts:decompressedPath}/src-prod/src/greengrass/version.sh {artifacts:decompressedPath}/src-prod/src/greengrass/recipe/prod.yaml`
          echo "[NinjaPCR] Run ver$VERSION"
          sh {configuration:/NINJAQPCR_SRC}/startup/startup.sh
          exit 0
      Shutdown:
        Script: |
          VERSION=`sh {artifacts:decompressedPath}/src-prod/src/greengrass/version.sh {artifacts:decompressedPath}/src-prod/src/greengrass/recipe/prod.yaml`
          echo "[NinjaPCR] Shutdown ver$VERSION"
      Recover: 
        Script: |
          VERSION=`sh {artifacts:decompressedPath}/src-prod/src/greengrass/version.sh {artifacts:decompressedPath}/src-prod/src/greengrass/recipe/prod.yaml`
          echo "[NinjaPCR] Recover ver$VERSION"
