#
# AWS IoT Greengrass component recipe reference
# https://docs.aws.amazon.com/greengrass/v2/developerguide/component-recipe-reference.html
#                  
RecipeFormatVersion: 2020-01-25
ComponentName: dev.hisa.Ninja-prod
ComponentVersion: '1.0.29'
ComponentDescription: Ninja qPCR Greengrass component
ComponentPublisher: Toriningen Inc.
ComponentConfiguration:
  DefaultConfiguration:
    NINJAQPCR_SRC: /usr/local/ninjaqpcr
    NINJAQPCR_DATA: /var/lib/ninjaqpcr/data
    NINJAQPCR_VERSION: 1.0.29
Manifests:
  - Platform:
      os: linux
    Artifacts:
      - URI: s3://gg-ninja-qpcr/artifacts/dev.hisa.Ninja/{configuration:/NINJAQPCR_VERSION}/src-prod.zip
        Unarchive: ZIP
    Lifecycle:
      Bootstrap:
        RequiresPrivilege: true
        Script: |
          echo "[NinjaPCR] Bootstrap ver{configuration:/NINJAQPCR_VERSION}"
          echo "configuration:/NINJAQPCR_SRC={configuration:/NINJAQPCR_SRC}"
          ln -f -s {artifacts:decompressedPath}/src-prod/src {configuration:/NINJAQPCR_SRC}
          cd {configuration:/NINJAQPCR_SRC}/qpcr
          echo y | npm update
          cd {configuration:/NINJAQPCR_SRC}/console/server
          echo y | npm update
          if [ `grep NINJAQPCR_VERSION /etc/profile | wc -l` -eq 0 ]; then
            echo "export NINJAQPCR_VERSION={configuration:/NINJAQPCR_VERSION}" | tee -a /etc/profile
          else
            sed -i "s/export NINJAQPCR_VERSION=.*/export NINJAQPCR_VERSION={configuration:/NINJAQPCR_VERSION}/" /etc/profile
          fi
          exit 0
      Install:
        # Sometimes rollback link to old version that's already removed. (we can remove this in future if it's only case with 1.0.25)
        Skipif: exists {configuration:/NINJAQPCR_SRC}
        Script: |
          echo "[NinjaPCR] Install ver{configuration:/NINJAQPCR_VERSION} MAKE LINK AGAIN"
          echo "configuration:/NINJAQPCR_SRC={configuration:/NINJAQPCR_SRC}"
          ln -f -s {artifacts:decompressedPath}/src-prod/src {configuration:/NINJAQPCR_SRC}
          cd {configuration:/NINJAQPCR_SRC}/qpcr
          echo y | npm update
          cd {configuration:/NINJAQPCR_SRC}/console/server
          echo y | npm update
          if [ `grep NINJAQPCR_VERSION /etc/profile | wc -l` -eq 0 ]; then
            echo "export NINJAQPCR_VERSION={configuration:/NINJAQPCR_VERSION}" | tee -a /etc/profile
          else
            sed -i "s/export NINJAQPCR_VERSION=.*/export NINJAQPCR_VERSION={configuration:/NINJAQPCR_VERSION}/" /etc/profile
          fi
          exit 0          
      Run:
        Script: |
          #python3 {configuration:/NINJAQPCR_SRC}/greengrass/recipe/hello_world2.py
          echo "[NinjaPCR] Run ver{configuration:/NINJAQPCR_VERSION}"
          sh {configuration:/NINJAQPCR_SRC}/startup/startup.sh
          exit 0
      Shutdown:
        Script: |
          echo "[NinjaPCR] Shutdown ver{configuration:/NINJAQPCR_VERSION}"
      Recover: 
        Script: |
          echo "[NinjaPCR] Recover ver{configuration:/NINJAQPCR_VERSION}"
