name: deploy-dev
on:
  push:
    branches:
      - 'master'
      - 'dev'
      - 'production'
    paths:
      - '**'
      - 'src/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to S3
        run: echo 'Sync to S3'
      - name: Call Lambda
        run: echo 'call Lambda'
      - name: Call Slack
        run: echo 'call Slack'

