name: deploy
on:
  push:
    branches:
      - 'batch'
      - 'prod'
    paths:
      - 'src/greengrass/recipe/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to S3
        run: echo 'Sync to S3'
      - name: Call Lambda
        run: echo 'call Lambda'
      - name: Call Slack
        run: echo 'call Slack'

